# https://docs.gradle.org/current/userguide/version_catalogs.html
[versions]
kotlin            = "2.1.21"
ksp               = "2.1.21-2.0.1"
kotlinx-serial    = "1.8.1"
junit5            = "5.12.2"

[libraries]
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serial" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines", version.ref = "kotlin" }
ksp-api                    = { module = "com.google.devtools.ksp:symbol-processing-api",    version.ref = "ksp" }
junit5-api                 = { module = "org.junit.jupiter:junit-jupiter-api",              version.ref = "junit5" }
junit5-engine              = { module = "org.junit.jupiter:junit-jupiter-engine",           version.ref = "junit5" }

[plugins]
kotlin-jvm           = { id = "org.jetbrains.kotlin.jvm",                  version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization",  version.ref = "kotlin" }
ksp                  = { id = "com.google.devtools.ksp",                    version.ref = "ksp" }
